#!/usr/bin/env bash

shopt -s globstar

hie_directory="$(dirname "${BASH_SOURCE[0]}")/../dist-newstyle"

if [ -d "${1}" ]; then
    cd "${1}"
fi

ormolu --mode="inplace" ./**/*.hs

if [ -f ".stan.toml" ]; then
    export STAN_USE_DEFAULT_CONFIG="True"
    stan --hiedir="$hie_directory" --short
fi

if [ -f "./weeder.dhall" ]; then
    weeder --hie-directory="$hie_directory"
fi

hlint .
