#!/usr/bin/env bash

function print_on_error() {
    tmp="$(mktemp)"
    if eval "$1" &> "$tmp"; then
        echo "${1%% *}: OK"
    else
        cat "$tmp"
    fi
    rm "$tmp"
}

project_root="$(dirname "${BASH_SOURCE[0]}")/.."

if [ -d "$1" ]; then
    cd "$1" || exit
fi

print_on_error "reuse lint"
print_on_error "nixpkgs-fmt '$project_root'"
print_on_error "shellcheck '$project_root'/scripts/*"

shopt -s globstar
GLOBIGNORE='**/dist-newstyle/**:dist-newstyle/**'
haskell_files=(./**/*.hs)

ormolu --mode="inplace" "${haskell_files[@]}"

print_on_error "cabal build all &> /dev/null"
hie_directory="$project_root/dist-newstyle"

if [ -f ".stan.toml" ]; then
    export STAN_USE_DEFAULT_CONFIG="True"
    stan --hiedir="$hie_directory" --short
fi

if [ -f "./weeder.dhall" ]; then
    print_on_error "weeder --hie-directory='$hie_directory'"
fi

print_on_error 'hlint .'
scan --check-spacing=False --join-comments=False "${haskell_files[@]}"
